target("llaisys-device-nvidia")
    set_kind("static")
    add_rules("cuda")
    add_values("cuda.rdc", false)
    set_languages("cxx17")
    set_warnings("all")
    add_cuflags("-Xcompiler=-fPIC", "-arch=native", {force = true})
    add_files("../src/device/nvidia/*.cu")

    on_install(function (target) end)
target_end()

target("llaisys-ops-nvidia")
    set_kind("static")
    add_deps("llaisys-tensor")
    add_rules("cuda")
    add_values("cuda.rdc", false)
    set_languages("cxx17")
    set_warnings("all")
    add_cuflags("-Xcompiler=-fPIC", "-arch=native", {force = true})
    add_files("../src/ops/*/nvidia/*.cu")

    on_install(function (target) end)
target_end()

target("llaisys-models-nvidia")
    set_kind("static")
    add_rules("cuda")
    add_values("cuda.rdc", false)
    set_languages("cxx17")
    set_warnings("all")
    add_cuflags("-Xcompiler=-fPIC", "-arch=native", {force = true})
    add_files("../src/models/*/*_nvidia.cu")

    on_install(function (target) end)
target_end()
